wandb_version: 1

seed:
  desc: null
  value: 100
dataset_path:
  desc: null
  value: ./dataset
device:
  desc: null
  value: cpu
train_percentage:
  desc: null
  value: 0.8
learning_rate:
  desc: null
  value: 0.01
optimizer:
  desc: null
  value: SGD
num_epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699227797.422301
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.0
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
